### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by mruvim** [zummenix/KeyboardWrapper#5]
Is there plans to add support for swift 3?

**Comment by zummenix** [comment]
Yes, of course. I will add swift 3 support as soon as I will have time. PR is welcome.

**Comment by zummenix** [comment]
@mruvim, the lib has been upgraded to swift 3 but unfortunately I wasn't able to push to cocoapods due to linting errors (related issue: https://github.com/CocoaPods/CocoaPods/issues/5796)

**Comment by zummenix** [comment]
I've pushed 3.0.1 https://cocoapods.org/pods/KeyboardWrapper
